### ISSUE TITLE
java.lang.NoSuchMethodError with Apache TinkerPop 3.4.5

### ISSUE THREAD

**Issue by deusama** [lambdazen/bitsy#23]
Steps to reproduce:

1. Clean installation of server v3.4.5 with bitsy plugins (ext/bitsy/plugin):
bitsy-3.2.2.jar
jackson-annotations-2.9.9.jar
jackson-core-2.9.9.jar
jackson-databind-2.9.9.jar
ness-core-1.9.1.jar

2. Configuration files
[gremlin-conf.txt](https://github.com/lambdazen/bitsy/files/4199119/gremlin-conf.txt)
[bitsy.properties.txt](https://github.com/lambdazen/bitsy/files/4199120/bitsy.properties.txt)

3. Create & list vertex
g.addV('Test').property('xxx', 42)
g.V()

4. Stack trace
[exception.txt](https://github.com/lambdazen/bitsy/files/4199153/exception.txt)

**Comment by conceptjs** [comment]
I'm guessing that this is related to the signature change HasContainer.testAll in December 2019. 

I will try to recompile Bitsy with 3.4.5 to see if that fixes the issue. Will let you know early next week.

Regards,

Sridhar.

**Comment by deusama** [comment]
Hi Sridhar, friendly reminder 😊

**Comment by lambdazen** [comment]
Sorry, am traveling for work. Will finish by this weekend.

**Comment by lambdazen** [comment]
Please let me know if version 3.3.1 of Bitsy fixes  your issue. I have built it with version 3.4.6 of Tinkerpop. 

Regards,

Sridhar.
