### ISSUE TITLE
Plan for new release

### ISSUE THREAD

**Issue by himanshumps** [lambdazen/bitsy#28]
Hi,

When are you planning to release 3.3.1 ?

Thanks,
Himanshu

**Comment by lambdazen** [comment]
I see the release here: https://mvnrepository.com/artifact/com.lambdazen.bitsy/bitsy/3.3.1

Am I missing something? 

Regards

Sridhar.

**Comment by himanshumps** [comment]
I was doing the search wrong in mvnrepo. Found it. Thanks
