### ISSUE TITLE
w/o commit Bitsy3 silently swallows changes?

### ISSUE THREAD

**Issue by cstamas** [lambdazen/bitsy#3]
Started using Bitsy w/o committing (is basically one huge tx that calls bitsy.shutdown() at the end). Added vertices/edges count is around 13k and 76k.

I noticed, that w/o doing `graph.tx().commit();` (tinkerpop3 API), Bitsy silently, w/o reporting anything, simply looses added vertices and edges. It does not complain, but simply the graph is incomplete at run end.

By adding this code (as TP3 Graph API is used)
```java
    if (graph.features().graph().supportsTransactions()) {
      graph.tx().commit();
    }
```
"fixes" Bitsy, and all the added vertices and edges are present at run end.

Is this intended behaviour? The fact that changes got _silently_ lost seems wrong to me.

**Comment by cstamas** [comment]
Closing for now, I think my use was invalid.

**Comment by a613** [comment]
Can you please elaborate?

**Comment by cstamas** [comment]
@a613 TP3 Transactions are elaborated here http://tinkerpop.apache.org/docs/current/reference/#transactions

Bitsy1.x did not support TX AFAIK, and this was changed when Bitsy 2.x got updated for TP3. @lambdazen  can you chime in?

**Comment by a613** [comment]
Ahh many thanks, that link had the answer. Ok, for posterity, I guess calling `.tx().open()` is unhelpful, and all you have to do is read/write to the graph, then call `.tx().commit()`!

**Comment by lambdazen** [comment]
Thanks Tamas. 

Alex: The behavior of transactions is based on the TP3 spec. Unless the commit is issued the data isn't saved to the graph.
