### ISSUE TITLE
pom version differs from release tag

### ISSUE THREAD

**Issue by giovibal** [lambdazen/bitsy#34]
It seems that release-3.4.1 has no congruent version in `pom.xml`

https://github.com/lambdazen/bitsy/blob/2f51117ec301f75b7356fc7105fc5fbad9483dde/pom.xml#L14

How can I help with this ?

**Comment by lambdazen** [comment]
Sorry about that. I found that pom.xml was not committed to Git on my local setup. 

Please let me know if this is fixed now: https://github.com/lambdazen/bitsy/blob/master/pom.xml

Regards,

Sridhar.

**Comment by giovibal** [comment]
Yes, now `master` is ok, but tag `release-3.4.1` continue to use 3.4.0 pom.
I think it'll adjust if you regenerate the 3.4.1 release.

For me it's not a problem, we can go ahead with 3.4.2.
We can close this issue after the 3.4.2 was correct releases.

**Comment by lambdazen** [comment]
Release 3.4.2 now includes your PR to compile against Gremlin 3.4.9. 

Thanks @giovibal
