### ISSUE TITLE
Q: Is it possible to make TextP.containing() be case-insensitive?

### ISSUE THREAD

**Issue by ihoro** [lambdazen/bitsy#36]
Hi,

Is it possible to configure Bitsy to do substring search in case-insensitive mode? e.g. for such queries:
```
g.V().has("property-name", TextP.containing("SubString"))
```

**Comment by sanketh-shetty-incontact** [comment]
Any help on this?

**Comment by lambdazen** [comment]
Please see if this snapshot compiled against 3.6.2 works for you. My guess is that Gremlin does a full scan on Bitsy and evaluates the text predicate across all matches. The latest published version compiles against 3.5.3

https://oss.sonatype.org/content/repositories/snapshots/com/lambdazen/bitsy/bitsy/3.6.2-SNAPSHOT/
