### ISSUE TITLE
Q: Whether TextP.regex(String) and TextP.notRegex(String) are already supported？

### ISSUE THREAD

**Issue by linjinying** [lambdazen/bitsy#40]
Hi,
 Two new additional TextP predicate members were added in the TinkerPop 3.6.0 release that allow working with regular expressions. These are TextP.regex and TextP.notRegex，does bitsy support this usage?

**Comment by linjinying** [comment]
Whether TextP.regex(String) and TextP.notRegex(String) are supported ？Could anyone help me out?

**Comment by lambdazen** [comment]
I compiled Bitsy against the 3.6.2 version of Tinkerpop. Please let me know if this JAR works for you, and I can make the official release. 

https://oss.sonatype.org/content/repositories/snapshots/com/lambdazen/bitsy/bitsy/3.6.2-SNAPSHOT/

**Comment by linjinying** [comment]
Yes, the compiled jar - bitsy-3.6.2-20230223.023156-1.jar  is very useful for me!!   By the way, is BitsyGraph(File dbPath) no longer supported in 3.6.2?  I upgraded from 3.4.2 and found that this method cannot be called...

**Comment by amumulin** [comment]
Will the code be submitted to the repository after the new version is released? How can we get your latest code?

**Comment by lambdazen** [comment]
I just release 3.6.2. Sorry for the delay.
